version: '3'

services:   
  app:
    container_name: ts-graphql
    restart: always
    build: .
    volumes:
      - ./:/usr/src/app
    environment: 
      - PORT=4000 
    ports: 
      - "4000:4000" 
    environment:
      NODE_ENV: development
    links: 
      - mongodb
    env_file: ./.env
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
  admin-mongo:
    image: 0x59/admin-mongo:latest
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - CONN_NAME=mongo
      - DB_HOST=mongo
